name: "mpi"

on:
  push:
    branches:
      - master
      - release/**
      - hotpatch/**
    paths:
    - "cmd/mpi/**.go"
    - "services/mpi/**.go"
    - "services/mpi/.semver.yaml"
    - ".github/workflows/mpi.yaml"
    - "configs/templates/dockerfile.tmpl"

jobs:
  prepare:
    name: Preparing build context
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        platform: [ ubuntu-latest ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - id: semrel
        name: Application Version
        shell: bash
        run: |
          go install github.com/maykonlf/semver-cli/cmd/semver@v1.0.2
          cd services/mpi/
          
          VERSION=$(semver get release)
          if [[ $(semver get alpha) != *-alpha.0 ]]; then
            VERSION=$(semver get alpha)
          elif [[ $(semver get beta) != *-beta.0 ]]; then
            VERSION=$(semver get beta)
          elif [[ $(semver get rc) != *-rc.0 ]]; then
            VERSION=$(semver get rc)
          fi
          
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          SHORT_COMM=$(git rev-parse --short HEAD)
          IMAGE_TAG="${VERSION}-${SHORT_COMM}"
          COMMIT_MSG="${{ github.event.head_commit.message == '**[release]**' }}"
          echo "${COMMIT_MSG}"
          IS_RELEASE="false"
          if [[ ${{ github.event.head_commit.message == '**[release]**' }} ]]; then
            IS_RELEASE="true"
          fi
          echo "${IS_RELEASE}"

          if [[ ${BRANCH_NAME} == release/** ]]; then
            IMAGE_TAG="${IMAGE_TAG}-release"
            if [[ ${IS_RELEASE} == true ]]; then
              IMAGE_TAG="${VERSION}"
            fi
          elif [[ ${BRANCH_NAME} == hotpatch/** ]]; then
            IMAGE_TAG="${IMAGE_TAG}-hotpatch"
            if [[ ${IS_RELEASE} == true ]]; then
              IMAGE_TAG="${VERSION}"
            fi
          fi
          
          echo "${IMAGE_TAG}"