name: "mpi"

on:
  push:
    branches:
      - master
      - release/**
      - hotpatch/**
#    paths:
#    - "cmd/mpi/**.go"
#    - "services/mpi/**.go"
#    - "services/mpi/.semver.yaml"
#    - ".github/workflows/mpi.yaml"
#    - "configs/templates/dockerfile.tmpl"

jobs:
  prepare:
    name: Preparing build context
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        platform: [ ubuntu-latest ]
    runs-on: ubuntu-latest
    steps:
      - name: Application Version
        id: semrel
        shell: bash
        run: |
          VERSION="v0.1.0"
          echo "${VERSION}"
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "${BRANCH_NAME}"
          SHORT_COMM=$(git rev-parse --short HEAD)
          echo "${SHORT_COMM}"
          echo "::set-output name=version::${{ github.ref == 'refs/heads/main' && '$VERSION-${SHORT_COMM}-develop' || '$VERSION' }}"
          IMAGE_TAG="${VERSION}-${SHORT_COMM}"
          if [[ ${BRANCH_NAME} == release/** ]]; then
            IMAGE_TAG="${VERSION}"
          elif [[ ${BRANCH_NAME} == hotpatch/** ]]; then
            IMAGE_TAG="${VERSION}-${SHORT_COMM}-hotpatch"
          fi
          echo "${IMAGE_TAG}"