name: "mpi"

on:
  push:
    branches:
      - master
      - release/**
      - hotpatch/**
#    paths:
#    - "cmd/mpi/**.go"
#    - "services/mpi/**.go"
#    - "services/mpi/.semver.yaml"
#    - ".github/workflows/mpi.yaml"
#    - "configs/templates/dockerfile.tmpl"

jobs:
  prepare:
    name: Preparing build context
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        platform: [ ubuntu-latest ]
    runs-on: ubuntu-latest
    steps:
      - name: Application Version
        id: semrel
        shell: bash
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "${BRANCH_NAME}"
          BUILD_TYPE="develop"
          if [[ ${BRANCH_NAME} == release/** ]]; then
            echo BUILD_TYPE="release"
          if [[ ${BRANCH_NAME} == hotpatch/** ]]; then
            echo BUILD_TYPE="patch"
          fi
#          echo "${BUILD_TYPE}"