name: "mpi"

on:
  push:
    branches:
      - master
      - "release/**"

jobs:
  prepare:
    if: "!contains(github.event.head_commit.message, 'Auto-release')"
    name: Preparing build context
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        platform: [ ubuntu-latest ]
    runs-on: ubuntu-latest
    steps:
      - name: Application Version
        id: semrel
        shell: bash
        run: |
          echo "hello"
          echo "${{ github.ref }}"
          echo ${GITHUB_REF#refs/heads/}
          if [[ ${{ github.ref }} == refs/heads/release/** ]]; then
            echo "release"
          else
            echo "master"
          fi