name: "mpi"

on:
  push:
    branches:
      - master
      - release/*
      - hotpatch/*
    paths:
    - "cmd/mpi/**.go"
    - "services/mpi/**.go"
#    - "services/mpi/.semver.yaml"
    - ".github/workflows/mpi.yaml"
    - "configs/templates/dockerfile.tmpl"
    tags:
      - mpi-v*

jobs:
  prepare:
    name: Preparing build context
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        platform: [ ubuntu-latest ]
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.semrel.outputs.version }}
    steps:
      - name: Application Version
        id: semrel
        shell: bash
        run: |
          IMAGE_TAG=v1
#          echo "::set-output name=version::${IMAGE_TAG}"
  build-push:
    name: Build and push
    needs: [ prepare ]
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Build, tag, and push image
        id: build-image
        shell: bash
        run: |
          TAG=${{ needs.prepare.outputs.RELEASE_VERSION }}
          if [[ ${TAG} == '' ]]; then
            echo "!!! needs.prepare.outputs.RELEASE_VERSION is empty"
            exit 1
          fi
      - name: Trigger deploy workflow
        if: "!contains(github.event.head_commit.message, '[no deploy]') && github.ref_name == 'master'"
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN_REPO_FULL_ACCESS }}
        run: |
          echo "deploying ..."
